// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Order struct {
	ID          int32     `json:"id"`
	CustomerID  int32     `json:"customer_id"`
	Username    string    `json:"username"`
	ProductName string    `json:"product_name"`
	OrderDate   time.Time `json:"order_date"`
	Status      string    `json:"status"`
	TotalAmount string    `json:"total_amount"`
}
