// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: order.sql

package sqlc

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, username, product_name, status) 
VALUES ($1, $2, $3, 'PENDING') RETURNING id, customer_id, username, product_name, order_date, status, total_amount
`

type CreateOrderParams struct {
	CustomerID  string `json:"customer_id"`
	Username    string `json:"username"`
	ProductName string `json:"product_name"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.CustomerID, arg.Username, arg.ProductName)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Username,
		&i.ProductName,
		&i.OrderDate,
		&i.Status,
		&i.TotalAmount,
	)
	return i, err
}
