// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountByEmail(ctx context.Context, email string) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
