// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
	"war_ticket/internal/domain"
)

type Event struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Location  string    `json:"location"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order = domain.Order

type OrderTicket struct {
	OrderID  int32 `json:"order_id"`
	TicketID int32 `json:"ticket_id"`
}

type Ticket = domain.Ticket

type TicketEvent struct {
	ID        int32     `json:"id"`
	EventID   int32     `json:"event_id"`
	TicketID  int32     `json:"ticket_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ApiKey   string `json:"api_key"`
	Username string `json:"username"`
}
