// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) error
	ListTickets(ctx context.Context) ([]Ticket, error)
	ListTicketsWithEvents(ctx context.Context) ([]TicketEvent, error)
}

var _ Querier = (*Queries)(nil)
